[project]
name = "glyph"
uuid = "cegyya7j6lsn78ftvos7pv5me"
version = "0.1.0"
description = "Error-correction codes"
source = "https://github.com/chaseruskin/glyph.git"
public = ["src"]
keywords = ["ecc", "code"]

[dependencies]
steel = { path = "../hysplabs/steel", version = "1" }

[project.metadata.test]
unit = [
    { dut = "parity", generics = { W = 5, EVEN = true } },
    { dut = "parity", generics = { W = 8, EVEN = false } },
    { dut = "hamming_enc", generics = {K = 4 } },
    { dut = "hamming_enc", generics = {K = 32 } },
    { dut = "hamming_enc", generics = {K = 64 } },
    { dut = "hamming_dec", generics = {K = 4 } },
    { dut = "hamming_dec", generics = {K = 32 } },
    { dut = "hamming_dec", generics = {K = 64 } },
]