# ------------------------------------------------------------------------------
# File: Intel DE10-Lite FPGA board file
# Version: 3.0.0
# About:
#   TOML file for mapping top-level ports to physical Intel FPGA pins. 
#
#   Code proceeding a '#' will be ignored. Pins have format "PIN_# = <PORT>". 
#   Mapping is processed in Quartus by adding a TCL command for assigning each
#   assigned pin during implementation (place-and-route).
#
# Usage:
#   1. Uncomment any pins to be assigned
#   2. Replace '__' with the port name found in the HDL top-level entity
#
# Help:
#   Manual: http://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&No=1021&PartNo=4
#   Schematic: https://faculty-web.msoe.edu/johnsontimoj/Common/FILES/de10-lite.pdf
#
# Revisions:
#   - Enforces .board to be TOML-syntax
#   - Makes .board an ini-syntax
#   - Single-line comments can be started as '#' or '#'
#   - Adds GPIO expansion header pins
#   - Adds required DEVICE and FAMILY assignments
#   - Adds SDRAM pins
#   - Adds VGA pins
#   - Fixes index descriptions on switches, buttons, and LEDS
# ------------------------------------------------------------------------------

[part]
# ----- Device -----------------------------------------------------------------
# NOTE: Required Quartus device settings for Intel DE10-Lite FPGA.
# ------------------------------------------------------------------------------
FAMILY = "MAX10"
DEVICE = "10M50DAF484C7G"

[pins]
# ----- Clocks -----------------------------------------------------------------
# ------------------------------------------------------------------------------
# PIN_P11 = __           # MAX10_CLK1_50 50 MHz clock input 3.3-V LVTTL
# PIN_N14 = __           # MAX10_CLK2_50 50 MHz clock input 3.3-V LVTTL
# PIN_N5  = __           # ADC_CLK_10    10 MHz clock input for ADC 3.3-V LVTTL


# ----- Push Buttons -----------------------------------------------------------
# NOTE: PRESS sends low logic level, RELEASE sends high logic level.
# ------------------------------------------------------------------------------
# PIN_B8 = __            # KEY0 Push-button[0] 3.3-V SCHMITT TRIGGER
# PIN_A7 = __            # KEY1 Push-button[1] 3.3-V SCHMITT TRIGGER


# ----- Switches ---------------------------------------------------------------
# NOTE: UP sends high logic level, DOWN sends low logic level.
# ------------------------------------------------------------------------------
PIN_C10 = "message[0]"           # SW0 Slide Switch[0] 3.3-V LVTTL
PIN_C11 = "message[1]"           # SW1 Slide Switch[1] 3.3-V LVTTL
PIN_D12 = "message[2]"           # SW2 Slide Switch[2] 3.3-V LVTTL
PIN_C12 = "message[3]"           # SW3 Slide Switch[3] 3.3-V LVTTL
# PIN_A12 = __           # SW4 Slide Switch[4] 3.3-V LVTTL
# PIN_B12 = __           # SW5 Slide Switch[5] 3.3-V LVTTL
# PIN_A13 = __           # SW6 Slide Switch[6] 3.3-V LVTTL
# PIN_A14 = __           # SW7 Slide Switch[7] 3.3-V LVTTL
# PIN_B14 = __           # SW8 Slide Switch[8] 3.3-V LVTTL
# PIN_F15 = __           # SW9 Slide Switch[9] 3.3-V LVTTL


# ----- LEDs -------------------------------------------------------------------
# NOTE: ON with high logic level, OFF with low logic level.
# ------------------------------------------------------------------------------
PIN_A8  = "encoding[0]"           # LEDR0 LED[0] 3.3-V LVTTL
PIN_A9  = "encoding[1]"           # LEDR1 LED[1] 3.3-V LVTTL
PIN_A10 = "encoding[2]"           # LEDR2 LED[2] 3.3-V LVTTL
PIN_B10 = "encoding[3]"           # LEDR3 LED[3] 3.3-V LVTTL
PIN_D13 = "encoding[4]"           # LEDR4 LED[4] 3.3-V LVTTL
PIN_C13 = "encoding[5]"           # LEDR5 LED[5] 3.3-V LVTTL
PIN_E14 = "encoding[6]"           # LEDR6 LED[6] 3.3-V LVTTL
PIN_D14 = "encoding[7]"           # LEDR7 LED[7] 3.3-V LVTTL
# PIN_A11 = __           # LEDR8 LED[8] 3.3-V LVTTL
# PIN_B11 = __           # LEDR9 LED[9] 3.3-V LVTTL
                            

# ----- 7-Segment Displays -----------------------------------------------------
# NOTE: ON with low logic level, OFF with high logic level.
#              0
#          ========
#     5  //      //  1
#       //  6   //
#       ========
#  4  //      //  2
#    //      //
#    ========    * DP 7
#       3
# ------------------------------------------------------------------------------
# PIN_C14 = __           # HEX00 Seven Segment Digit 0[0] 3.3-V LVTTL
# PIN_E15 = __           # HEX01 Seven Segment Digit 0[1] 3.3-V LVTTL
# PIN_C15 = __           # HEX00 Seven Segment Digit 0[2] 3.3-V LVTTL
# PIN_C16 = __           # HEX01 Seven Segment Digit 0[3] 3.3-V LVTTL
# PIN_E16 = __           # HEX02 Seven Segment Digit 0[4] 3.3-V LVTTL
# PIN_D17 = __           # HEX03 Seven Segment Digit 0[5] 3.3-V LVTTL
# PIN_C17 = __           # HEX04 Seven Segment Digit 0[6] 3.3-V LVTTL
# PIN_D15 = __           # HEX05 Seven Segment Digit 0[7], DP 3.3-V LVTTL

# PIN_C18 = __           # HEX10 Seven Segment Digit 1[0] 3.3-V LVTTL
# PIN_D18 = __           # HEX11 Seven Segment Digit 1[1] 3.3-V LVTTL
# PIN_E18 = __           # HEX12 Seven Segment Digit 1[2] 3.3-V LVTTL
# PIN_B16 = __           # HEX13 Seven Segment Digit 1[3] 3.3-V LVTTL
# PIN_A17 = __           # HEX14 Seven Segment Digit 1[4] 3.3-V LVTTL
# PIN_A18 = __           # HEX15 Seven Segment Digit 1[5] 3.3-V LVTTL
# PIN_B17 = __           # HEX16 Seven Segment Digit 1[6] 3.3-V LVTTL
# PIN_A16 = __           # HEX17 Seven Segment Digit 1[7], DP 3.3-V LVTTL

# PIN_B20 = __           # HEX20 Seven Segment Digit 2[0] 3.3-V LVTTL
# PIN_A20 = __           # HEX21 Seven Segment Digit 2[1] 3.3-V LVTTL
# PIN_B19 = __           # HEX22 Seven Segment Digit 2[2] 3.3-V LVTTL
# PIN_A21 = __           # HEX23 Seven Segment Digit 2[3] 3.3-V LVTTL
# PIN_B21 = __           # HEX24 Seven Segment Digit 2[4] 3.3-V LVTTL
# PIN_C22 = __           # HEX25 Seven Segment Digit 2[5] 3.3-V LVTTL
# PIN_B22 = __           # HEX26 Seven Segment Digit 2[6] 3.3-V LVTTL
# PIN_A19 = __           # HEX27 Seven Segment Digit 2[7], DP 3.3-V LVTTL

# PIN_F21 = __           # HEX30 Seven Segment Digit 3[0] 3.3-V LVTTL
# PIN_E22 = __           # HEX31 Seven Segment Digit 3[1] 3.3-V LVTTL
# PIN_E21 = __           # HEX32 Seven Segment Digit 3[2] 3.3-V LVTTL
# PIN_C19 = __           # HEX33 Seven Segment Digit 3[3] 3.3-V LVTTL
# PIN_C20 = __           # HEX34 Seven Segment Digit 3[4] 3.3-V LVTTL
# PIN_D19 = __           # HEX35 Seven Segment Digit 3[5] 3.3-V LVTTL
# PIN_E17 = __           # HEX36 Seven Segment Digit 3[6] 3.3-V LVTTL
# PIN_D22 = __           # HEX37 Seven Segment Digit 3[7], DP 3.3-V LVTTL

# PIN_F18 = __           # HEX40 Seven Segment Digit 4[0] 3.3-V LVTTL
# PIN_E20 = __           # HEX41 Seven Segment Digit 4[1] 3.3-V LVTTL
# PIN_E19 = __           # HEX42 Seven Segment Digit 4[2] 3.3-V LVTTL
# PIN_J18 = __           # HEX43 Seven Segment Digit 4[3] 3.3-V LVTTL
# PIN_H19 = __           # HEX44 Seven Segment Digit 4[4] 3.3-V LVTTL
# PIN_F19 = __           # HEX45 Seven Segment Digit 4[5] 3.3-V LVTTL
# PIN_F20 = __           # HEX46 Seven Segment Digit 4[6] 3.3-V LVTTL
# PIN_F17 = __           # HEX47 Seven Segment Digit 4[7], DP 3.3-V LVTTL

# PIN_J20 = __           # HEX50 Seven Segment Digit 5[0] 3.3-V LVTTL
# PIN_K20 = __           # HEX51 Seven Segment Digit 5[1] 3.3-V LVTTL
# PIN_L18 = __           # HEX52 Seven Segment Digit 5[2] 3.3-V LVTTL
# PIN_N18 = __           # HEX53 Seven Segment Digit 5[3] 3.3-V LVTTL
# PIN_M20 = __           # HEX54 Seven Segment Digit 5[4] 3.3-V LVTTL
# PIN_N19 = __           # HEX55 Seven Segment Digit 5[5] 3.3-V LVTTL
# PIN_N20 = __           # HEX56 Seven Segment Digit 5[6] 3.3-V LVTTL
# PIN_L19 = __           # HEX57 Seven Segment Digit 5[7], DP 3.3-V LVTTL


# ----- Video Graphics Array (VGA) ---------------------------------------------
#                Horizontal   Vertical
# configuration | VGA(60Hz)  | VGA(60Hz)
# resolution    | 640x480    | 640x480
# sync pulse    | 96         | 2
# back porch    | 48         | 33
# visible area  | 640        | 480
# front porch   | 16         | 10
# total         | 800        | 525
# pixel clock   | 25MHz      | 25MHz
# NOTE: sync pulses are active-low.
# NOTE: drive low logic level to RGB data outputs when not in the visible area.
# ------------------------------------------------------------------------------
# PIN_AA1 = __           # VGA_R0 VGA Red[0] 3.3-V LVTTL
# PIN_V1  = __           # VGA_R1 VGA Red[1] 3.3-V LVTTL
# PIN_Y2  = __           # VGA_R2 VGA Red[2] 3.3-V LVTTL
# PIN_Y1  = __           # VGA_R3 VGA Red[3] 3.3-V LVTTL
# PIN_W1  = __           # VGA_G0 VGA Green[0] 3.3-V LVTTL
# PIN_T2  = __           # VGA_G1 VGA Green[1] 3.3-V LVTTL
# PIN_R2  = __           # VGA_G2 VGA Green[2] 3.3-V LVTTL
# PIN_R1  = __           # VGA_G3 VGA Green[3] 3.3-V LVTTL
# PIN_P1  = __           # VGA_B0 VGA Blue[0] 3.3-V LVTTL
# PIN_T1  = __           # VGA_B1 VGA Blue[1] 3.3-V LVTTL
# PIN_P4  = __           # VGA_B2 VGA Blue[2] 3.3-V LVTTL
# PIN_N2  = __           # VGA_B3 VGA Blue[3] 3.3-V LVTTL
# PIN_N3  = __           # VGA_HS VGA Horizontal sync 3.3-V LVTTL
# PIN_N1  = __           # VGA_VS VGA Vertical sync 3.3-V LVTTL


# ----- Synchronous Dynamic Random-Access Memory (SDRAM) -----------------------
# NOTE: 64MB size, with 16-bits stored at each address.
# ------------------------------------------------------------------------------
# PIN_U17  = __          # DRAM_ADDR0  SDRAM Address[0] 3.3-V LVTTL
# PIN_W19  = __          # DRAM_ADDR1  SDRAM Address[1] 3.3-V LVTTL
# PIN_V18  = __          # DRAM_ADDR2  SDRAM Address[2] 3.3-V LVTTL
# PIN_U18  = __          # DRAM_ADDR3  SDRAM Address[3] 3.3-V LVTTL
# PIN_U19  = __          # DRAM_ADDR4  SDRAM Address[4] 3.3-V LVTTL
# PIN_T18  = __          # DRAM_ADDR5  SDRAM Address[5] 3.3-V LVTTL
# PIN_T19  = __          # DRAM_ADDR6  SDRAM Address[6] 3.3-V LVTTL
# PIN_R18  = __          # DRAM_ADDR7  SDRAM Address[7] 3.3-V LVTTL
# PIN_P18  = __          # DRAM_ADDR8  SDRAM Address[8] 3.3-V LVTTL
# PIN_P19  = __          # DRAM_ADDR9  SDRAM Address[9] 3.3-V LVTTL
# PIN_T20  = __          # DRAM_ADDR10 SDRAM Address[10] 3.3-V LVTTL
# PIN_P20  = __          # DRAM_ADDR11 SDRAM Address[11] 3.3-V LVTTL
# PIN_R20  = __          # DRAM_ADDR12 SDRAM Address[12] 3.3-V LVTTL
# PIN_Y21  = __          # DRAM_DQ0    SDRAM Data[0] 3.3-V LVTTL
# PIN_Y20  = __          # DRAM_DQ1    SDRAM Data[1] 3.3-V LVTTL
# PIN_AA22 = __          # DRAM_DQ2    SDRAM Data[2] 3.3-V LVTTL
# PIN_AA21 = __          # DRAM_DQ3    SDRAM Data[3] 3.3-V LVTTL
# PIN_Y22  = __          # DRAM_DQ4    SDRAM Data[4] 3.3-V LVTTL
# PIN_W22  = __          # DRAM_DQ5    SDRAM Data[5] 3.3-V LVTTL
# PIN_W20  = __          # DRAM_DQ6    SDRAM Data[6] 3.3-V LVTTL
# PIN_V21  = __          # DRAM_DQ7    SDRAM Data[7] 3.3-V LVTTL
# PIN_P21  = __          # DRAM_DQ8    SDRAM Data[8] 3.3-V LVTTL
# PIN_J22  = __          # DRAM_DQ9    SDRAM Data[9] 3.3-V LVTTL
# PIN_H21  = __          # DRAM_DQ10   SDRAM Data[10] 3.3-V LVTTL
# PIN_H22  = __          # DRAM_DQ11   SDRAM Data[11] 3.3-V LVTTL
# PIN_G22  = __          # DRAM_DQ12   SDRAM Data[12] 3.3-V LVTTL
# PIN_G20  = __          # DRAM_DQ13   SDRAM Data[13] 3.3-V LVTTL
# PIN_G19  = __          # DRAM_DQ14   SDRAM Data[14] 3.3-V LVTTL
# PIN_F22  = __          # DRAM_DQ15   SDRAM Data[15] 3.3-V LVTTL
# PIN_T21  = __          # DRAM_BA0    SDRAM Bank Address[0] 3.3-V LVTTL
# PIN_T22  = __          # DRAM_BA1    SDRAM Bank Address[1] 3.3-V LVTTL
# PIN_V22  = __          # DRAM_LDQM   SDRAM byte Data Mask[0] 3.3-V LVTTL
# PIN_J21  = __          # DRAM_UDQM   SDRAM byte Data Mask[1] 3.3-V LVTTL
# PIN_U22  = __          # DRAM_RAS_N  SDRAM Row Address Strobe 3.3-V LVTTL
# PIN_U21  = __          # DRAM_CAS_N  SDRAM Column Address Strobe 3.3-V LVTTL
# PIN_N22  = __          # DRAM_CKE    SDRAM Clock Enable 3.3-V LVTTL
# PIN_L14  = __          # DRAM_CLK    SDRAM Clock 3.3-V LVTTL
# PIN_V20  = __          # DRAM_WE_N   SDRAM Write Enable 3.3-V LVTTL
# PIN_U20  = __          # DRAM_CS_N   SDRAM Chip Select 3.3-V LVTTL


# ----- GPIO Expansion Headers -------------------------------------------------
# NOTE: JP1# arranged as tall column and read left -> right, top -> bottom.
# ------------------------------------------------------------------------------
# PIN_V10 = __           # GPIO_0  GPIO Connection [0] 3.3-V LVTTL
# PIN_W10 = __           # GPIO_1  GPIO Connection [1] 3.3-V LVTTL
# PIN_V9  = __           # GPIO_2  GPIO Connection [2] 3.3-V LVTTL
# PIN_W9  = __           # GPIO_3  GPIO Connection [3] 3.3-V LVTTL
# PIN_V8  = __           # GPIO_4  GPIO Connection [4] 3.3-V LVTTL
# PIN_W8  = __           # GPIO_5  GPIO Connection [5] 3.3-V LVTTL
# PIN_V7  = __           # GPIO_6  GPIO Connection [6] 3.3-V LVTTL
# PIN_W7  = __           # GPIO_7  GPIO Connection [7] 3.3-V LVTTL
# PIN_W6  = __           # GPIO_8  GPIO Connection [8] 3.3-V LVTTL
# PIN_V5  = __           # GPIO_9  GPIO Connection [9] 3.3-V LVTTL
#                        # 5-V
#                        # GND
# PIN_W5   = __          # GPIO_10 GPIO Connection [10] 3.3-V LVTTL
# PIN_AA15 = __          # GPIO_11 GPIO Connection [11] 3.3-V LVTTL
# PIN_AA14 = __          # GPIO_12 GPIO Connection [12] 3.3-V LVTTL
# PIN_W13  = __          # GPIO_13 GPIO Connection [13] 3.3-V LVTTL
# PIN_W12  = __          # GPIO_14 GPIO Connection [14] 3.3-V LVTTL
# PIN_AB13 = __          # GPIO_15 GPIO Connection [15] 3.3-V LVTTL
# PIN_AB12 = __          # GPIO_16 GPIO Connection [16] 3.3-V LVTTL
# PIN_Y11  = __          # GPIO_17 GPIO Connection [17] 3.3-V LVTTL
# PIN_AB11 = __          # GPIO_18 GPIO Connection [18] 3.3-V LVTTL
# PIN_W11  = __          # GPIO_19 GPIO Connection [19] 3.3-V LVTTL
# PIN_AB10 = __          # GPIO_20 GPIO Connection [20] 3.3-V LVTTL
# PIN_AA10 = __          # GPIO_21 GPIO Connection [21] 3.3-V LVTTL
# PIN_AA9  = __          # GPIO_22 GPIO Connection [22] 3.3-V LVTTL
# PIN_Y8   = __          # GPIO_23 GPIO Connection [23] 3.3-V LVTTL
# PIN_AA8  = __          # GPIO_24 GPIO Connection [24] 3.3-V LVTTL
# PIN_Y7   = __          # GPIO_25 GPIO Connection [25] 3.3-V LVTTL
#                        # 3.3-V
#                        # GND
# PIN_AA7 = __           # GPIO_26 GPIO Connection [26] 3.3-V LVTTL
# PIN_Y6  = __           # GPIO_27 GPIO Connection [27] 3.3-V LVTTL
# PIN_AA6 = __           # GPIO_28 GPIO Connection [28] 3.3-V LVTTL
# PIN_Y5  = __           # GPIO_29 GPIO Connection [29] 3.3-V LVTTL
# PIN_AA5 = __           # GPIO_30 GPIO Connection [30] 3.3-V LVTTL
# PIN_Y4  = __           # GPIO_31 GPIO Connection [31] 3.3-V LVTTL
# PIN_AB3 = __           # GPIO_32 GPIO Connection [32] 3.3-V LVTTL
# PIN_Y3  = __           # GPIO_33 GPIO Connection [33] 3.3-V LVTTL
# PIN_AB2 = __           # GPIO_34 GPIO Connection [34] 3.3-V LVTTL
# PIN_AA2 = __           # GPIO_35 GPIO Connection [35] 3.3-V LVTTL